name: pokedex
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'


dependencies:
  network:
    path: packages/network
  authentication_repository:
    path: packages/authentication_repository
  pokemon_repository:
    path: packages/pokemon_repository
  flutter:
    sdk: flutter

  flutter_colorpicker: ^1.0.3
  uuid: ^3.0.6
  smooth_page_indicator: ^1.0.0+2
  shared_preferences: ^2.0.15
  go_router: ^10.0.0
  firebase_auth: ^4.4.0
  equatable: ^2.0.5
  flutter_bloc: ^8.1.2
  flutter_form_builder: ^9.1.0
  firebase: ^9.0.3
  firebase_core: ^2.9.0
  flutter_native_splash: ^2.3.1

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  

  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true
  assets:
    - assets/pokedex_assets/

