name: pokemon_repository
description: Dart package which manages the pokemon domain.
publish_to: none

environment:
  sdk: '>=3.0.5 <4.0.0'


dependencies:
  network:
    path: ../network
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  shared_preferences: ^2.0.15
  